# Generated by Django 5.0.6 on 2024-07-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remains',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
